// dsa_system.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module dsa_system (
		input  wire        clk_clk,                             //                          clk.clk
		output wire [9:0]  pio_leds_external_connection_export, // pio_leds_external_connection.export
		input  wire        reset_reset,                         //                        reset.reset
		output wire [12:0] sdram_addr,                          //                        sdram.addr
		output wire [1:0]  sdram_ba,                            //                             .ba
		output wire        sdram_cas_n,                         //                             .cas_n
		output wire        sdram_cke,                           //                             .cke
		output wire        sdram_cs_n,                          //                             .cs_n
		inout  wire [15:0] sdram_dq,                            //                             .dq
		output wire [1:0]  sdram_dqm,                           //                             .dqm
		output wire        sdram_ras_n,                         //                             .ras_n
		output wire        sdram_we_n                           //                             .we_n
	);

	wire         dsa_avalon_wrapper_0_avalon_master_waitrequest;                  // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_waitrequest -> dsa_avalon_wrapper_0:avm_mem_waitrequest
	wire  [31:0] dsa_avalon_wrapper_0_avalon_master_readdata;                     // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_readdata -> dsa_avalon_wrapper_0:avm_mem_readdata
	wire  [31:0] dsa_avalon_wrapper_0_avalon_master_address;                      // dsa_avalon_wrapper_0:avm_mem_address -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_address
	wire         dsa_avalon_wrapper_0_avalon_master_read;                         // dsa_avalon_wrapper_0:avm_mem_read -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_read
	wire   [3:0] dsa_avalon_wrapper_0_avalon_master_byteenable;                   // dsa_avalon_wrapper_0:avm_mem_byteenable -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_byteenable
	wire         dsa_avalon_wrapper_0_avalon_master_readdatavalid;                // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_readdatavalid -> dsa_avalon_wrapper_0:avm_mem_readdatavalid
	wire         dsa_avalon_wrapper_0_avalon_master_write;                        // dsa_avalon_wrapper_0:avm_mem_write -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_write
	wire  [31:0] dsa_avalon_wrapper_0_avalon_master_writedata;                    // dsa_avalon_wrapper_0:avm_mem_writedata -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_master_writedata
	wire  [31:0] jtag_master_master_readdata;                                     // mm_interconnect_0:jtag_master_master_readdata -> jtag_master:master_readdata
	wire         jtag_master_master_waitrequest;                                  // mm_interconnect_0:jtag_master_master_waitrequest -> jtag_master:master_waitrequest
	wire  [31:0] jtag_master_master_address;                                      // jtag_master:master_address -> mm_interconnect_0:jtag_master_master_address
	wire         jtag_master_master_read;                                         // jtag_master:master_read -> mm_interconnect_0:jtag_master_master_read
	wire   [3:0] jtag_master_master_byteenable;                                   // jtag_master:master_byteenable -> mm_interconnect_0:jtag_master_master_byteenable
	wire         jtag_master_master_readdatavalid;                                // mm_interconnect_0:jtag_master_master_readdatavalid -> jtag_master:master_readdatavalid
	wire         jtag_master_master_write;                                        // jtag_master:master_write -> mm_interconnect_0:jtag_master_master_write
	wire  [31:0] jtag_master_master_writedata;                                    // jtag_master:master_writedata -> mm_interconnect_0:jtag_master_master_writedata
	wire  [31:0] mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_readdata;    // dsa_avalon_wrapper_0:avs_ctrl_readdata -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_readdata
	wire         mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_waitrequest; // dsa_avalon_wrapper_0:avs_ctrl_waitrequest -> mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_waitrequest
	wire   [3:0] mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_address;     // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_address -> dsa_avalon_wrapper_0:avs_ctrl_address
	wire         mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_read;        // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_read -> dsa_avalon_wrapper_0:avs_ctrl_read
	wire         mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_write;       // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_write -> dsa_avalon_wrapper_0:avs_ctrl_write
	wire  [31:0] mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_writedata;   // mm_interconnect_0:dsa_avalon_wrapper_0_avalon_slave_writedata -> dsa_avalon_wrapper_0:avs_ctrl_writedata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_chipselect;          // mm_interconnect_0:new_sdram_controller_0_s1_chipselect -> new_sdram_controller_0:az_cs
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_readdata;            // new_sdram_controller_0:za_data -> mm_interconnect_0:new_sdram_controller_0_s1_readdata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_waitrequest;         // new_sdram_controller_0:za_waitrequest -> mm_interconnect_0:new_sdram_controller_0_s1_waitrequest
	wire  [24:0] mm_interconnect_0_new_sdram_controller_0_s1_address;             // mm_interconnect_0:new_sdram_controller_0_s1_address -> new_sdram_controller_0:az_addr
	wire         mm_interconnect_0_new_sdram_controller_0_s1_read;                // mm_interconnect_0:new_sdram_controller_0_s1_read -> new_sdram_controller_0:az_rd_n
	wire   [1:0] mm_interconnect_0_new_sdram_controller_0_s1_byteenable;          // mm_interconnect_0:new_sdram_controller_0_s1_byteenable -> new_sdram_controller_0:az_be_n
	wire         mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid;       // new_sdram_controller_0:za_valid -> mm_interconnect_0:new_sdram_controller_0_s1_readdatavalid
	wire         mm_interconnect_0_new_sdram_controller_0_s1_write;               // mm_interconnect_0:new_sdram_controller_0_s1_write -> new_sdram_controller_0:az_wr_n
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_writedata;           // mm_interconnect_0:new_sdram_controller_0_s1_writedata -> new_sdram_controller_0:az_data
	wire         mm_interconnect_0_pio_leds_s1_chipselect;                        // mm_interconnect_0:pio_leds_s1_chipselect -> pio_leds:chipselect
	wire  [31:0] mm_interconnect_0_pio_leds_s1_readdata;                          // pio_leds:readdata -> mm_interconnect_0:pio_leds_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_leds_s1_address;                           // mm_interconnect_0:pio_leds_s1_address -> pio_leds:address
	wire         mm_interconnect_0_pio_leds_s1_write;                             // mm_interconnect_0:pio_leds_s1_write -> pio_leds:write_n
	wire  [31:0] mm_interconnect_0_pio_leds_s1_writedata;                         // mm_interconnect_0:pio_leds_s1_writedata -> pio_leds:writedata

	DSA_Avalon_Wrapper #(
		.N (4)
	) dsa_avalon_wrapper_0 (
		.clk                   (clk_clk),                                                         //         clock.clk
		.reset_n               (~reset_reset),                                                    //         reset.reset_n
		.avs_ctrl_address      (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_address),     //  avalon_slave.address
		.avs_ctrl_read         (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_read),        //              .read
		.avs_ctrl_write        (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_write),       //              .write
		.avs_ctrl_writedata    (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_writedata),   //              .writedata
		.avs_ctrl_readdata     (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_readdata),    //              .readdata
		.avs_ctrl_waitrequest  (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_waitrequest), //              .waitrequest
		.avm_mem_address       (dsa_avalon_wrapper_0_avalon_master_address),                      // avalon_master.address
		.avm_mem_read          (dsa_avalon_wrapper_0_avalon_master_read),                         //              .read
		.avm_mem_write         (dsa_avalon_wrapper_0_avalon_master_write),                        //              .write
		.avm_mem_writedata     (dsa_avalon_wrapper_0_avalon_master_writedata),                    //              .writedata
		.avm_mem_byteenable    (dsa_avalon_wrapper_0_avalon_master_byteenable),                   //              .byteenable
		.avm_mem_waitrequest   (dsa_avalon_wrapper_0_avalon_master_waitrequest),                  //              .waitrequest
		.avm_mem_readdata      (dsa_avalon_wrapper_0_avalon_master_readdata),                     //              .readdata
		.avm_mem_readdatavalid (dsa_avalon_wrapper_0_avalon_master_readdatavalid)                 //              .readdatavalid
	);

	dsa_system_jtag_master #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtag_master (
		.clk_clk              (clk_clk),                          //          clk.clk
		.clk_reset_reset      (reset_reset),                      //    clk_reset.reset
		.master_address       (jtag_master_master_address),       //       master.address
		.master_readdata      (jtag_master_master_readdata),      //             .readdata
		.master_read          (jtag_master_master_read),          //             .read
		.master_write         (jtag_master_master_write),         //             .write
		.master_writedata     (jtag_master_master_writedata),     //             .writedata
		.master_waitrequest   (jtag_master_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (jtag_master_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (jtag_master_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                                  // master_reset.reset
	);

	dsa_system_new_sdram_controller_0 new_sdram_controller_0 (
		.clk            (clk_clk),                                                   //   clk.clk
		.reset_n        (~reset_reset),                                              // reset.reset_n
		.az_addr        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_new_sdram_controller_0_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_new_sdram_controller_0_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_new_sdram_controller_0_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_addr),                                                //  wire.export
		.zs_ba          (sdram_ba),                                                  //      .export
		.zs_cas_n       (sdram_cas_n),                                               //      .export
		.zs_cke         (sdram_cke),                                                 //      .export
		.zs_cs_n        (sdram_cs_n),                                                //      .export
		.zs_dq          (sdram_dq),                                                  //      .export
		.zs_dqm         (sdram_dqm),                                                 //      .export
		.zs_ras_n       (sdram_ras_n),                                               //      .export
		.zs_we_n        (sdram_we_n)                                                 //      .export
	);

	dsa_system_pio_leds pio_leds (
		.clk        (clk_clk),                                  //                 clk.clk
		.reset_n    (~reset_reset),                             //               reset.reset_n
		.address    (mm_interconnect_0_pio_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_leds_s1_readdata),   //                    .readdata
		.out_port   (pio_leds_external_connection_export)       // external_connection.export
	);

	dsa_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                          (clk_clk),                                                         //                                        clk_0_clk.clk
		.dsa_avalon_wrapper_0_reset_reset_bridge_in_reset_reset (reset_reset),                                                     // dsa_avalon_wrapper_0_reset_reset_bridge_in_reset.reset
		.jtag_master_clk_reset_reset_bridge_in_reset_reset      (reset_reset),                                                     //      jtag_master_clk_reset_reset_bridge_in_reset.reset
		.dsa_avalon_wrapper_0_avalon_master_address             (dsa_avalon_wrapper_0_avalon_master_address),                      //               dsa_avalon_wrapper_0_avalon_master.address
		.dsa_avalon_wrapper_0_avalon_master_waitrequest         (dsa_avalon_wrapper_0_avalon_master_waitrequest),                  //                                                 .waitrequest
		.dsa_avalon_wrapper_0_avalon_master_byteenable          (dsa_avalon_wrapper_0_avalon_master_byteenable),                   //                                                 .byteenable
		.dsa_avalon_wrapper_0_avalon_master_read                (dsa_avalon_wrapper_0_avalon_master_read),                         //                                                 .read
		.dsa_avalon_wrapper_0_avalon_master_readdata            (dsa_avalon_wrapper_0_avalon_master_readdata),                     //                                                 .readdata
		.dsa_avalon_wrapper_0_avalon_master_readdatavalid       (dsa_avalon_wrapper_0_avalon_master_readdatavalid),                //                                                 .readdatavalid
		.dsa_avalon_wrapper_0_avalon_master_write               (dsa_avalon_wrapper_0_avalon_master_write),                        //                                                 .write
		.dsa_avalon_wrapper_0_avalon_master_writedata           (dsa_avalon_wrapper_0_avalon_master_writedata),                    //                                                 .writedata
		.jtag_master_master_address                             (jtag_master_master_address),                                      //                               jtag_master_master.address
		.jtag_master_master_waitrequest                         (jtag_master_master_waitrequest),                                  //                                                 .waitrequest
		.jtag_master_master_byteenable                          (jtag_master_master_byteenable),                                   //                                                 .byteenable
		.jtag_master_master_read                                (jtag_master_master_read),                                         //                                                 .read
		.jtag_master_master_readdata                            (jtag_master_master_readdata),                                     //                                                 .readdata
		.jtag_master_master_readdatavalid                       (jtag_master_master_readdatavalid),                                //                                                 .readdatavalid
		.jtag_master_master_write                               (jtag_master_master_write),                                        //                                                 .write
		.jtag_master_master_writedata                           (jtag_master_master_writedata),                                    //                                                 .writedata
		.dsa_avalon_wrapper_0_avalon_slave_address              (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_address),     //                dsa_avalon_wrapper_0_avalon_slave.address
		.dsa_avalon_wrapper_0_avalon_slave_write                (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_write),       //                                                 .write
		.dsa_avalon_wrapper_0_avalon_slave_read                 (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_read),        //                                                 .read
		.dsa_avalon_wrapper_0_avalon_slave_readdata             (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_readdata),    //                                                 .readdata
		.dsa_avalon_wrapper_0_avalon_slave_writedata            (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_writedata),   //                                                 .writedata
		.dsa_avalon_wrapper_0_avalon_slave_waitrequest          (mm_interconnect_0_dsa_avalon_wrapper_0_avalon_slave_waitrequest), //                                                 .waitrequest
		.new_sdram_controller_0_s1_address                      (mm_interconnect_0_new_sdram_controller_0_s1_address),             //                        new_sdram_controller_0_s1.address
		.new_sdram_controller_0_s1_write                        (mm_interconnect_0_new_sdram_controller_0_s1_write),               //                                                 .write
		.new_sdram_controller_0_s1_read                         (mm_interconnect_0_new_sdram_controller_0_s1_read),                //                                                 .read
		.new_sdram_controller_0_s1_readdata                     (mm_interconnect_0_new_sdram_controller_0_s1_readdata),            //                                                 .readdata
		.new_sdram_controller_0_s1_writedata                    (mm_interconnect_0_new_sdram_controller_0_s1_writedata),           //                                                 .writedata
		.new_sdram_controller_0_s1_byteenable                   (mm_interconnect_0_new_sdram_controller_0_s1_byteenable),          //                                                 .byteenable
		.new_sdram_controller_0_s1_readdatavalid                (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid),       //                                                 .readdatavalid
		.new_sdram_controller_0_s1_waitrequest                  (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),         //                                                 .waitrequest
		.new_sdram_controller_0_s1_chipselect                   (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),          //                                                 .chipselect
		.pio_leds_s1_address                                    (mm_interconnect_0_pio_leds_s1_address),                           //                                      pio_leds_s1.address
		.pio_leds_s1_write                                      (mm_interconnect_0_pio_leds_s1_write),                             //                                                 .write
		.pio_leds_s1_readdata                                   (mm_interconnect_0_pio_leds_s1_readdata),                          //                                                 .readdata
		.pio_leds_s1_writedata                                  (mm_interconnect_0_pio_leds_s1_writedata),                         //                                                 .writedata
		.pio_leds_s1_chipselect                                 (mm_interconnect_0_pio_leds_s1_chipselect)                         //                                                 .chipselect
	);

endmodule
